name: Update Spotify Section

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        if [ -n "$SPOTIFY_CLIENT_ID" ]; then
          echo "SPOTIFY_CLIENT_ID is set"
        else
          echo "SPOTIFY_CLIENT_ID is NOT set"
        fi
        if [ -n "$SPOTIFY_CLIENT_SECRET" ]; then
          echo "SPOTIFY_CLIENT_SECRET is set"
        else
        echo "SPOTIFY_CLIENT_SECRET is NOT set"
        fi
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_SECRET }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: pip install PyGithub requests python-dotenv

    - name: Run Spotify Script
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python spotify_query.py
